### ISSUE TITLE
Segfaults on very large songs

### ISSUE THREAD

**Issue by DaVince** [uyjulian/spc2it#1]
I just converted all Lufia 2 SPCs with the tool, and there was a single one it it wouldn't take. The file would process right up until the 100% mark and then segfault. My guess is that the song was too long to contain inside the IT file, as it contains the entire intro song of the game, which is around 6:50 long.

The file in question is `102 Rumbling.spc` from the following archive:
http://www.zophar.net/music/spc/lufia-ii-rise-of-the-sinistrals-[estpolis-denki-ii]-[lufia].html

The original OpenSPC would export approximately 6 minutes and 10 seconds of this song and then end. In other words, it saved an incomplete version of the song to IT rather than crashing.

**Comment by uyjulian** [comment]
I'll check that out.

**Comment by DaVince** [comment]
That fixed it, it exports now. But instead, there seems to be a new problem: the song ends at pattern 102; the rest of the patterns up to 206 just consist of complete silence. Pattern 206 itself contains the forced instrument stop commands. So it seems like the song has already long ended and yet _still_ asks for more patterns for some reason.

**Comment by uyjulian** [comment]
Yeah, I'll check to trim the pattern later on.
