### ISSUE TITLE
PATH_MAX undeclared identifier

### ISSUE THREAD

**Issue by jeffythedragonslayer** [uyjulian/spc2it#19]
When I try to build this with the "meson compile -C build" command on windows, I get these errors:

```
Activating VS 16.11.2
ninja: Entering directory `build'
[1/2] Compiling C object spc2it.exe.p/main.c.obj
FAILED: spc2it.exe.p/main.c.obj
"cl" "-Ispc2it.exe.p" "-I." "-I.." "/MDd" "/nologo" "/showIncludes" "/W2" "/O2" "/Gw" "/Zi" "/Fdspc2it.exe.p\main.c.pdb" /Fospc2it.exe.p/main.c.obj "/c" ../main.c
../main.c(60): error C2065: 'PATH_MAX': undeclared identifier
../main.c(60): error C2057: expected constant expression
../main.c(60): error C2466: cannot allocate an array of constant size 0
../main.c(60): error C2133: 'fn': unknown size
../main.c(156): error C2065: 'PATH_MAX': undeclared identifier
ninja: build stopped: subcommand failed.
```

**Comment by uyjulian** [comment]
The specified build environment and commands are located here: <https://github.com/uyjulian/spc2it/blob/master/.github/workflows/ci.yml#L53>
If you want to add support for alternative build environment, I accept pull requests

**Comment by jeffythedragonslayer** [comment]
I'm confused.  Line 47 is build-win32 but it's followed by Ubuntu
commands.  Do you mean that you support building inside WSL when on
windows, but not native windows?

**Comment by uyjulian** [comment]
Yes, that is correct

**Comment by jeffythedragonslayer** [comment]
Thank you.
