### ISSUE TITLE
One instrument is missing from Final Fight 3

### ISSUE THREAD

**Issue by RyanBram** [uyjulian/spc2it#2]
Hi, Julian.
Thanks for creating a great and opensource software. Now I can listen my favorites SNES  music from many device that support Module playback.

I just want to report a minor issue related to your software. When I convert my Final Fight 3 OST to Impulse Tracker, there are always one missing instrument  in the resulted .it file, especially the first instrument.

I attached all of the file here (please try to convert "Law and Disorder" title): 
[*Attachment*](http://www.zophar.net/download_file/24721)

Best regards

**Comment by uyjulian** [comment]
Which build are you using? I fixed the first note problem a long time ago, try again with v0.3

**Comment by RyanBram** [comment]
Hi, Thanks for reply.
I tried your last release (v0.3). Most of SNES title is Ok. Only some Final Fight 3 which seems not converted well.
Please try my attachment first and you'll understand what I mean, because I cannot give better explanation in English.

Regards

**Comment by uyjulian** [comment]
Okay, I know the problem, but it will take me a while to fix it (static update rate = not good!)
Thanks for the report

**Comment by uyjulian** [comment]
Superseded by #3
